title: Mikolaj Rozkrut 
logo: /assets/img/profile.png
description: **LinkedIn:** [linkedin.com/in/mikolaj-rozkrut](www.linkedin.com/in/mikolaj-rozkrut) 
show downloads: true 
theme: jekyll-theme-minimal
