title: Mikolaj Rozkrut 
logo: /assets/img/Circle_image-min.png
#description: **LinkedIn:** [linkedin.com/in/mikolaj-rozkrut](www.linkedin.com/in/mikolaj-rozkrut) 
show downloads: true 
theme: jekyll-theme-minimal
